apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-k8s-resources/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - keycloak-k8s-resources/kubernetes/kubernetes.yml
  - keycloak-k8s-resources/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  # Patch to namespace "keycloak-operator"
  - patches/crb.yml

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: KUBERNETES_NAMESPACE
          value: "keycloak"
    target:
      kind: Deployment
      name: keycloak-operator