apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: keycloak-operator
    targetRevision: feat/first-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: keycloak/manifests
    targetRevision: feat/first-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: postgres-operator/postgres-operator/charts/postgres-operator
    targetRevision: feat/first-tools
    helm:
      releaseName: postgres-operator
      valueFiles:
        - ../../../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: prometheus-operator/helm-charts/charts/kube-prometheus-stack
    targetRevision: feat/first-tools
    helm:
      releaseName: prometheus-operator
      valueFiles:
        - ../../../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: grafana-operator/grafana-operator/deploy/helm/grafana-operator
    targetRevision: feat/first-tools
    helm:
      releaseName: grafana-operator
      valueFiles:
        - ../../../../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: grafana
    targetRevision: feat/first-tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   name: rook
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
#     path: rook
#     targetRevision: feat/first-tools
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: metrics-server/metrics-server/charts/metrics-server
    targetRevision: feat/first-tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # fix "metadata.annotations: Too long"
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: longhorn/longhorn/chart
    targetRevision: feat/first-tools
    helm:
      releaseName: longhorn
      valueFiles:
        - ../../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        crds:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: metallb/metallb/charts/metallb
    targetRevision: feat/first-tools
    helm:
      releaseName: metallb
      valueFiles:
        - ../../../values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metallb-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: metallb/manifests
    targetRevision: feat/first-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
