apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: keycloak-operator
    targetRevision: feat/add-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: keycloak/manifests
    targetRevision: feat/add-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      chart: postgres-operator
      targetRevision: 1.14.0
      helm:
        valueFiles:
        - $values/postgres-operator/values.yaml
    -  repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
       path: postgres-operator
       targetRevision: feat/add-tools
       ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.8.1
      helm:
        valueFiles:
        - $values/prometheus-operator/values.yaml
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: prometheus-operator
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana-operator
      targetRevision: 5.17.0
      helm:
        valueFiles:
        - $values/grafana-operator/values.yaml
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: grafana-operator
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # fix "metadata.annotations: Too long"
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: grafana
    targetRevision: feat/add-tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   name: rook
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
#     path: rook
#     targetRevision: feat/add-tools
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/metrics-server'
      targetRevision: 3.12.2
      chart: metrics-server
      helm:
        helm:
          valueFiles:
              - $values/metrics-server/values.yaml
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: metrics-server
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # fix "metadata.annotations: Too long"
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: 1.8.1
      chart: longhorn
      helm:
        valueFiles:
          - $values/longhorn/values.yaml
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: longhorn
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.17.1
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: cert-manager
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # fix "metadata.annotations: Too long"
      - ServerSideApply=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
     - repoURL: https://metallb.github.io/metallb
       chart: metallb
       targetRevision: 0.14.9
       helm:
         valuesFiles:
           - $values/metallb/values.yaml
     - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
       path: metallb
       targetRevision: feat/add-tools
       ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metallb-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: metallb/manifests
    targetRevision: feat/add-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.0
      helm:
        valueFiles:
          - $values/ingress-nginx/values.yaml 
    - repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
      path: ingress-nginx
      targetRevision: feat/add-tools
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mrcs25/cluster-bootstrap.git'
    path: prometheus
    targetRevision: feat/add-tools
    directory:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground